name: Build PDF

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Copy
        run: |
          mkdir build
          cp ./main.pdf ./build/thesis.pdf
      # - name: Upload PDF
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: main
      #     path: ./main.pdf
      - name: Deploy orphan branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: build
          force_orphan: true
